POST http://account_payments_api.test/api/accounts/ HTTP/1.1
Accept: application/json
content-type: application/json

{
}



###

GET http://account_payments_api.test/api/accounts/ HTTP/1.1


###

GET http://account_payments_api.test/api/accounts/3 HTTP/1.1

###

DELETE http://account_payments_api.test/api/accounts/2 HTTP/1.1


####

POST http://account_payments_api.test/api/payments/ HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "account_id": 7,
    "amount": 1200
}

###

GET http://account_payments_api.test/api/payments/ HTTP/1.1

###

DELETE http://account_payments_api.test/api/payments/3 HTTP/1.1
